Merge of xfs-cmds-2.4.18:slinx:111136a by nathans.
  bump to version 2.0.0 for extended attribute and other interface changes.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -105,6 +105,13 @@ AC_CHECK_HEADER(xfs/handle.h,, [
 	echo 'Alternatively, run "make install-dev" from the xfsprogs source.'
 	exit 1
 ])
+AC_CHECK_LIB(handle, attr_list_by_handle,, [
+	echo
+	echo 'FATAL ERROR: could not find a current XFS handle library.'
+	echo 'Upgrade the xfsprogs-devel (rpm) or the xfslibs-dev (deb) package.'
+	echo 'Alternatively, run "make install-dev" from the xfsprogs source.'
+	exit 1
+])
 
 dnl ensure libtool is installed
 AC_PATH_PROG(LIBTOOL, libtool,,/usr/bin)
