change the way we interact with libtool and do .deb packaging for consistency between all packages.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,11 +3,6 @@ AC_INIT(include/dmapi.h)
 pkg_name="dmapi"
 AC_SUBST(pkg_name)
 
-# For libtool
-AC_PROG_LIBTOOL
-AC_SUBST(LIBTOOL_DEPS)
-AC_SUBST(enable_shared)
-
 #
 # Note: the following environment variables may be set to override the
 # defaults (to change paths and/or executables, build parameters, etc):
@@ -40,13 +35,7 @@ pkg_release=$PKG_BUILD
 AC_SUBST(pkg_version)
 AC_SUBST(pkg_release)
 
-# For libtool versioning.
-pkg_lt_version=${PKG_LT_CURRENT}.${PKG_LT_REVISION}.${PKG_LT_AGE}
-pkg_lt_current=$PKG_LT_CURRENT
-AC_SUBST(pkg_lt_version)
-AC_SUBST(pkg_lt_current)
-
-pkg_distribution="SGI ProPack"
+pkg_distribution="SGI XFS"
 test -z "$DISTRIBUTION" || pkg_distribution="$DISTRIBUTION"
 AC_SUBST(pkg_distribution)
 
@@ -116,6 +105,23 @@ AC_CHECK_HEADER(xfs/handle.h,, [
 	exit 1
 ])
 
+dnl ensure libtool is installed
+AC_PATH_PROG(LIBTOOL, libtool,,/usr/bin)
+if test "$LIBTOOL" = ""; then
+	echo
+	echo 'FATAL ERROR: libtool does not seem to be installed.'
+	echo $pkg_name cannot be built without a working libtool installation.
+	exit 1
+fi
+libtool=$LIBTOOL
+AC_SUBST(libtool)
+
+dnl libtool to build libraries static only?
+AC_ARG_ENABLE(enable_shared,
+	[ --enable-shared=[yes/no]	Enable use of shared libraries [default=yes].],
+	,
+	enable_shared=yes)
+AC_SUBST(enable_shared)
 
 dnl alternate root and usr prefixes
 test -z "$ROOT_PREFIX" && ROOT_PREFIX=""
@@ -167,13 +173,6 @@ AC_SUBST(pkg_doc_dir)
 dnl
 dnl output files
 dnl
-
-#For libtool, from section 5.4.2 of the libtool manual.  Just in
-# case we ever need them.
-LTLIBOBJS=`echo "$LIBOBJS" | sed 's/\.[^.]* /.lo /g;s/\.[^.]*$/.lo/'`
-AC_SUBST(LTLIBOBJS)
-LTALLOCA=`echo "$ALLOCA" | sed 's/\.[^.]* /.lo /g;s/\.[^.]*$/.lo/'`
-AC_SUBST(LTALLOCA)
 
 AC_OUTPUT( \
 dnl  Build definitions for use in Makefiles
